### ISSUE TITLE
Proposal: Integrating Command Aliases for Ease of Use

### ISSUE THREAD

**Issue by Macktireh** [Tobi-De/falco#87]
Hello,

I hope you are doing well. This project is really cool and I appreciate your work. I'm looking forward to it being stable. I wanted to ask if you could consider adding aliases for the commands?

Thank you in advance.

**Comment by Tobi-De** [comment]
Hi @Macktireh

> I wanted to ask if you could consider adding aliases for the commands?

I'm guessing you are talking about aliases for the scripts that come with a generated project and not Falco itself. Right now, I'm thinking of moving every script to use [just](https://github.com/casey/just) (only for the scripts obviously) instead of hatch . The just file will come with some aliases, and it would be quite easy to add new ones.
